### PR TITLE
Changed how the emoji is verified.

### PR DESCRIPTION
**Pull request by Sarveshmrao**
#### Information

> Check one

- [ ] This includes major changes (breaking changes)
- [ ] This includes minor changes (minimal usage changes, minor new features)
- [X] This includes patches (bug fixes, documentation changes etc)

#### Is this related to an issue?

> Reference any issues here

#### Changes made

When using custom emoji the line where the code checks if the emoji reacted is same as the emoji in config the script stops resulting in no new ticket creation.
To rectify this I have added a new variable `emoji` which is the emoji name appended with emoji ID so that the script is not stopped. In config, the panel reacts with emoji only if we put the name followed by its ID (eg: :name:123456576875) and in the IF statement the verification stops because of `r.emoji.name` gives only and `r.emoji.id` gives only the ID which is obviously not same as the `config.panel.reaction`.

#### Confirmations

> Check all that apply

- [ ] I have updated any necessary documentation
- [X] This uses consistent code style
- [X] This is tested and works

### CODE REVIEW

**Comment by eartharoid** [comment]
Wouldn't this change break using default Unicode emojis though?

Anyway, I'm fairly certain you can already use custom emoji if you just put the numerical ID in the config rather than the full ID, so `'475749578877173763'` instead of `:earth:475749578877173763`. I think that's why it compares `r.emoji.name` and `r.emoji.id` to the config, `name` is for Unicode and `id` is for the ID of a custom emoji.

Thank you for your time though! 😃

**Comment by Sarveshmrao** [comment]
Sorry I forgot about the unicode emojis. But using only the ID for customer emoji didn't work for me.

**Comment by eartharoid** [comment]
The custom emoji needs to be in from the same guild, you can't use emoji from other guilds.

**Comment by Sarveshmrao** [comment]
Yeah I know that. 
It's in the guild and it works if I put the full ID but doesn't work if I put the numerical ID or the emoji name.

**Comment by eartharoid** [comment]
oh 🤔

**Comment by Sarveshmrao** [comment]
If possible please put the `hactoberfest-accepted` label. If possible and if you want.

**Comment by eartharoid** [comment]
Please join the [support server](https://go.eartharoid.me/discord) so I can help you with it not working with the custom emoji ID.

**Pull request closed without merging**
