### PR TITLE
remove.js New Moderation Features Added

### PR DESCRIPTION
**Pull request by NamVr**
#### New Moderation Features Added for removing people.

> Check one

- [ ] This includes major changes (breaking changes)
- [X] This includes minor changes (minimal usage changes, minor new features)
- [ ] This includes patches (bug fixes, documentation changes etc)

#### Is this related to an issue?

Well no, this is custom request and would look cool for people, making the bot more interactive.

#### Changes made
Check the changelog of these files for detailed explanation.
1. remove.js
2. config.js

#### Confirmations

> Check all that apply

- [ ] I have updated any necessary documentation
- [X] This uses consistent code style
- [X] This is tested and works

### CODE REVIEW

**Review by eartharoid — CHANGES_REQUESTED** [review]
Hi, thanks for contributing, however, I don't really see the point of the changes. It's already impossible to remove the server owner, and I think the ticket creator should be allowed to remove a staff member they don't trust or are reporting within the ticket.

Either way, storing the IDs in the config isn't the best way. The owner ID can be fetched from the guild object, and it'd be better to check if the member has the staff role rather than having the `mod` options.

**Comment by eartharoid** [comment]
If you still want to contribute, you can have a go at #56 if you want.

**Comment by NamVr** [comment]
I know about this. But think like this:

- Someone joined your server and opened a ticket request.
- He removed your moderators and moderation bot.
- Then he can easily swear or advertise, sending invite links and all, this feature can be useful if we do the Mod IDs as MOD bots, so the person gets a stop on advertising spam and swear because he can't remove the bot.

As it is, I am confused, because doing contributions for the first time, can you tell me what should I do?

**Comment by eartharoid** [comment]
I think I understand what you mean, but it's still quite pointless as if someone did that they'd be sending invites etc in a channel that only the staff can see anyway.
Thanks for your time though :)

**Comment by NamVr** [comment]
Nevermind, welcome.
It's your wish though, I modified for my server, so thought sending a change via PR.

**Pull request closed without merging**
